# Generated by Django 4.2.16 on 2024-09-27 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dataCollector", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModifiedQA_ZRE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_relation", models.CharField(max_length=255)),
                ("modified_question", models.TextField()),
                ("modified_subject", models.CharField(max_length=255)),
                ("modified_context", models.TextField()),
                ("modified_answers", models.JSONField()),
                (
                    "original",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifications",
                        to="dataCollector.qa_zre",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModifiedCounterfact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_case_id", models.IntegerField()),
                ("modified_pararel_idx", models.IntegerField()),
                ("modified_paraphrase_prompts", models.JSONField()),
                ("modified_neighborhood_prompts", models.JSONField()),
                ("modified_attribute_prompts", models.JSONField()),
                ("modified_generation_prompts", models.JSONField()),
                (
                    "modified_requested_rewrite",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modified_rewrite",
                        to="dataCollector.requestedrewrite",
                    ),
                ),
                (
                    "original",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifications",
                        to="dataCollector.counterfact",
                    ),
                ),
            ],
        ),
    ]
