# Generated by Django 4.2.16 on 2024-09-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataCollector", "0002_modifiedqa_zre_modifiedcounterfact"),
    ]

    operations = [
        migrations.AddField(
            model_name="modifiedcounterfact",
            name="is_modified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="modifiedqa_zre",
            name="is_modified",
            field=models.BooleanField(default=False),
        ),
    ]
