# Generated by Django 4.2.16 on 2024-09-27 02:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dataCollector", "0003_modifiedcounterfact_is_modified_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="modifiedcounterfact",
            old_name="modified_attribute_prompts",
            new_name="attribute_prompts",
        ),
        migrations.RenameField(
            model_name="modifiedcounterfact",
            old_name="modified_case_id",
            new_name="case_id",
        ),
        migrations.RenameField(
            model_name="modifiedcounterfact",
            old_name="modified_generation_prompts",
            new_name="generation_prompts",
        ),
        migrations.RenameField(
            model_name="modifiedcounterfact",
            old_name="modified_neighborhood_prompts",
            new_name="neighborhood_prompts",
        ),
        migrations.RenameField(
            model_name="modifiedcounterfact",
            old_name="modified_paraphrase_prompts",
            new_name="paraphrase_prompts",
        ),
        migrations.RenameField(
            model_name="modifiedcounterfact",
            old_name="modified_pararel_idx",
            new_name="pararel_idx",
        ),
        migrations.RenameField(
            model_name="modifiedcounterfact",
            old_name="modified_requested_rewrite",
            new_name="requested_rewrite",
        ),
        migrations.RenameField(
            model_name="modifiedqa_zre",
            old_name="modified_answers",
            new_name="answers",
        ),
        migrations.RenameField(
            model_name="modifiedqa_zre",
            old_name="modified_context",
            new_name="context",
        ),
        migrations.RenameField(
            model_name="modifiedqa_zre",
            old_name="modified_question",
            new_name="question",
        ),
        migrations.RenameField(
            model_name="modifiedqa_zre",
            old_name="modified_relation",
            new_name="relation",
        ),
        migrations.RenameField(
            model_name="modifiedqa_zre",
            old_name="modified_subject",
            new_name="subject",
        ),
    ]
