# Generated by Django 4.2.16 on 2024-09-27 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "dataCollector",
            "0004_rename_modified_attribute_prompts_modifiedcounterfact_attribute_prompts_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ModificationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_object", models.CharField(max_length=255)),
                ("object_id", models.IntegerField()),
                (
                    "modification_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("previous_values", models.JSONField()),
                ("new_values", models.JSONField()),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
