# Generated by Django 4.2.16 on 2024-10-12 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dataCollector", "0005_modificationhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modificationhistory",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="modifiedcounterfact",
            name="original",
        ),
        migrations.RemoveField(
            model_name="modifiedcounterfact",
            name="requested_rewrite",
        ),
        migrations.RemoveField(
            model_name="modifiedqa_zre",
            name="original",
        ),
        migrations.RemoveField(
            model_name="requestedrewrite",
            name="target_new",
        ),
        migrations.RemoveField(
            model_name="requestedrewrite",
            name="target_true",
        ),
        migrations.DeleteModel(
            name="Counterfact",
        ),
        migrations.DeleteModel(
            name="ModificationHistory",
        ),
        migrations.DeleteModel(
            name="ModifiedCounterfact",
        ),
        migrations.DeleteModel(
            name="ModifiedQA_ZRE",
        ),
        migrations.DeleteModel(
            name="QA_ZRE",
        ),
        migrations.DeleteModel(
            name="RequestedRewrite",
        ),
        migrations.DeleteModel(
            name="Target",
        ),
    ]
